plugin: aws_ec2
aws_profile: default
regions:
  - us-east-1  
keyed_groups:
  - key: tag:Name 
    prefix: tag_Name_
  - prefix: instance_type
    key: instance_type
  - key: placement.region
    prefix: aws_region
hostvars: 
  - host: "*"
    vars: 
      ansible_user: ec2-user 
      ansible_ssh_private_key_file: /home/ahmedsamy/Desktop/devops/03-project-3/jenkins-key.pem
compose:
  ansible_host: public_ip_address